package ports

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

// Generic .env variable names. Per-port vars derive from the port name via
// EnvVarForPort (e.g. `app` -> `APP_PORT`); the BASE_URL family derives
// from the `app` port.
const (
	EnvApp              = "APP_PORT"
	EnvBaseURL          = "BASE_URL"
	EnvWebhooksBaseURL  = "WEBHOOKS_BASE_URL"
	EnvAllowedWSOrigins = "ALLOWED_WS_ORIGINS"
	// EnvAppURL is the gateway URL for a worktree
	// (http://<slug>.<domain>[:port]); ensured only when proxy.enabled.
	EnvAppURL = "APP_URL"
)

// EnvFileName is the generated file name inside each worktree.
const EnvFileName = ".env"

// EnvVarForPort maps a port name to its .env variable (e.g. `app` ->
// `APP_PORT`, `web` -> `WEB_PORT`). Non-alphanumeric runs become a single
// underscore so names like `api-v2` stay valid shell identifiers.
func EnvVarForPort(name string) string {
	var b strings.Builder
	prevUnderscore := true // leading trim: avoid a leading underscore
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToUpper(r))
			prevUnderscore = false
		} else if !prevUnderscore {
			b.WriteByte('_')
			prevUnderscore = true
		}
	}
	s := strings.Trim(b.String(), "_")
	if s == "" {
		return "PORT"
	}
	return s + "_PORT"
}

// appPort extracts the app port for derived URLs.
func appPort(ports map[string]int) (int, error) {
	v, ok := ports[PortApp]
	if !ok {
		return 0, fmt.Errorf("render .env: missing port %q", PortApp)
	}
	return v, nil
}

// AppURL builds http://<slug>.<domain>[:port] for a worktree gateway.
// Port 80 is omitted; empty domain defaults to localhost.
func AppURL(slug, domain string, gatewayPort int) string {
	d := strings.ToLower(strings.Trim(strings.TrimSpace(domain), "."))
	if d == "" {
		d = "localhost"
	}
	s := strings.ToLower(strings.TrimSpace(slug))
	if gatewayPort == 80 {
		return "http://" + s + "." + d
	}
	if gatewayPort <= 0 || gatewayPort > 65535 {
		return "http://" + s + "." + d
	}
	return "http://" + s + "." + d + ":" + fmt.Sprintf("%d", gatewayPort)
}

// EnsureKeys appends missing extra keys (e.g. APP_URL) under the managed
// header without touching existing lines. It returns the keys added.
func EnsureKeys(worktreePath string, extra map[string]string) (added []string, err error) {
	if len(extra) == 0 {
		return nil, nil
	}
	if worktreePath == "" {
		return nil, fmt.Errorf("write .env: empty worktree path")
	}
	path := filepath.Join(worktreePath, EnvFileName)
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read .env %q: %w", path, err)
	}
	content, added, _ := fillMissing(string(raw), extra)
	if len(added) > 0 {
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return nil, fmt.Errorf("write .env %q: %w", path, err)
		}
	}
	return added, nil
}

// ManagedValues maps every wrk3-managed .env variable to its value for
// the given allocation: one <NAME>_PORT per port plus the BASE_URL family
// derived from the app port.
func ManagedValues(ports map[string]int) (map[string]string, error) {
	app, err := appPort(ports)
	if err != nil {
		return nil, err
	}
	out := make(map[string]string, len(ports)+3)
	for name, v := range ports {
		out[EnvVarForPort(name)] = fmt.Sprintf("%d", v)
	}
	origin := fmt.Sprintf("http://localhost:%d", app)
	out[EnvBaseURL] = origin
	out[EnvWebhooksBaseURL] = origin
	out[EnvAllowedWSOrigins] = origin
	return out, nil
}

// managedHeader marks the appended block in pre-existing .env files.
const managedHeader = "# Managed by wrk3 — port allocations (other lines preserved)."

// generatedHeader is written only for fresh .env files. Pre-existing files
// keep their own content; missing managed keys are appended under
// managedHeader and existing values are never modified.
const generatedHeader = "# Generated by wrk3 — do not edit."

// parseKey extracts the variable name from a .env assignment line.
// It reports ok=false for blank lines, comments, and non-assignments.
// It tolerates `export KEY=...`, surrounding whitespace, and `KEY = ...`.
func parseKey(line string) (key string, ok bool) {
	trimmed := strings.TrimSpace(strings.TrimSuffix(line, "\r"))
	if trimmed == "" || strings.HasPrefix(trimmed, "#") {
		return "", false
	}
	rest := trimmed
	if strings.HasPrefix(rest, "export") && len(rest) > len("export") &&
		(rest[len("export")] == ' ' || rest[len("export")] == '\t') {
		rest = strings.TrimSpace(rest[len("export"):])
	}
	idx := strings.Index(rest, "=")
	if idx < 0 {
		return "", false
	}
	key = strings.TrimSpace(rest[:idx])
	if key == "" {
		return "", false
	}
	for i, r := range key {
		if r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r) {
			if i == 0 && unicode.IsDigit(r) {
				return "", false
			}
			continue
		}
		return "", false
	}
	return key, true
}

// splitComment splits a post-= value into value and trailing comment.
// Only ` <space>#` starts a comment so URLs and quoted `#` survive.
func splitComment(after string) (before, comment string) {
	for i := 0; i < len(after); i++ {
		if after[i] == '#' && i > 0 && (after[i-1] == ' ' || after[i-1] == '\t') {
			return strings.TrimRight(after[:i], " \t"), after[i:]
		}
	}
	return after, ""
}

// normValue normalizes a raw post-= value for comparison: it strips any
// trailing ` # comment`, surrounding whitespace, and one layer of matching
// single or double quotes. `APP_PORT="8000" # old` thus equals `8000`.
func normValue(after string) string {
	v, _ := splitComment(after)
	v = strings.TrimSpace(v)
	if len(v) >= 2 {
		if (v[0] == '"' && v[len(v)-1] == '"') || (v[0] == '\'' && v[len(v)-1] == '\'') {
			v = v[1 : len(v)-1]
		}
	}
	return v
}

// assignmentValue returns the normalized value of key's first assignment in
// line, or ok=false when line does not assign key. It tolerates
// `export KEY=...` and surrounding whitespace like parseKey.
func assignmentValue(line, key string) (value string, ok bool) {
	trimmed := strings.TrimSpace(strings.TrimSuffix(line, "\r"))
	if trimmed == "" || strings.HasPrefix(trimmed, "#") {
		return "", false
	}
	rest := trimmed
	if strings.HasPrefix(rest, "export") && len(rest) > len("export") &&
		(rest[len("export")] == ' ' || rest[len("export")] == '\t') {
		rest = strings.TrimSpace(rest[len("export"):])
	}
	idx := strings.Index(rest, "=")
	if idx < 0 {
		return "", false
	}
	if strings.TrimSpace(rest[:idx]) != key {
		return "", false
	}
	return normValue(rest[idx+1:]), true
}

// Render builds the .env file content for ports. Every entry in ports
// becomes <NAME>_PORT (sorted by port name for stable output); BASE_URL,
// WEBHOOKS_BASE_URL, and ALLOWED_WS_ORIGINS derive from the app port
// as http://localhost:<appPort>.
func Render(ports map[string]int) (string, error) {
	if len(ports) == 0 {
		return "", fmt.Errorf("render .env: no ports allocated")
	}
	app, err := appPort(ports)
	if err != nil {
		return "", err
	}
	names := make([]string, 0, len(ports))
	for name := range ports {
		names = append(names, name)
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString(generatedHeader + "\n")
	for _, name := range names {
		fmt.Fprintf(&b, "%s=%d\n", EnvVarForPort(name), ports[name])
	}
	origin := fmt.Sprintf("http://localhost:%d", app)
	fmt.Fprintf(&b, "%s=%s\n", EnvBaseURL, origin)
	fmt.Fprintf(&b, "%s=%s\n", EnvWebhooksBaseURL, origin)
	fmt.Fprintf(&b, "%s=%s\n", EnvAllowedWSOrigins, origin)
	return b.String(), nil
}

// fillMissing appends managed keys absent from content under managedHeader
// and reports what it found. Existing lines are never modified: keys already
// present keep their values, even when they differ from the allocation —
// those are reported as diverged so callers can warn instead of overwrite.
func fillMissing(content string, desired map[string]string) (out string, added []string, diverged map[string]string) {
	// Normalize CRLF to LF for processing; callers write back LF.
	crlf := strings.Contains(content, "\r\n")
	body := strings.ReplaceAll(content, "\r\n", "\n")
	lines := strings.Split(body, "\n")
	present := make(map[string]string, len(desired))
	for _, line := range lines {
		key, ok := parseKey(line)
		if !ok {
			continue
		}
		if _, managed := desired[key]; !managed {
			continue
		}
		if _, seen := present[key]; seen {
			continue
		}
		if v, ok := assignmentValue(line, key); ok {
			present[key] = v
		}
	}
	var missing []string
	diverged = make(map[string]string)
	for k, want := range desired {
		got, ok := present[k]
		if !ok {
			missing = append(missing, k)
			continue
		}
		if got != want {
			diverged[k] = got
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		added = append([]string(nil), missing...)
		// Drop the trailing empty element from Split so we control newlines.
		if len(lines) > 0 && lines[len(lines)-1] == "" {
			lines = lines[:len(lines)-1]
		}
		if len(lines) > 0 && lines[len(lines)-1] != "" {
			lines = append(lines, "")
		}
		hasMarker := false
		for _, l := range lines {
			if strings.TrimSpace(l) == managedHeader {
				hasMarker = true
				break
			}
		}
		if !hasMarker {
			lines = append(lines, managedHeader)
		}
		for _, k := range missing {
			lines = append(lines, k+"="+desired[k])
		}
	}
	out = strings.Join(lines, "\n")
	if out != "" && !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	if crlf {
		out = strings.ReplaceAll(out, "\n", "\r\n")
	}
	return out, added, diverged
}

// checkPorts validates an allocation for .env use.
func checkPorts(ports map[string]int) error {
	if len(ports) == 0 {
		return fmt.Errorf("render .env: no ports allocated")
	}
	if _, err := appPort(ports); err != nil {
		return err
	}
	return nil
}

// Ensure guarantees <worktreePath>/.env contains the wrk3-managed port
// section: missing files are created via Render, existing files gain only
// the managed keys they lack (appended under managedHeader). Existing lines
// are never modified or deleted. It returns the keys added and the managed
// keys already present with a different value (diverged: left intact).
func Ensure(worktreePath string, ports map[string]int) (added []string, diverged map[string]string, err error) {
	if worktreePath == "" {
		return nil, nil, fmt.Errorf("write .env: empty worktree path")
	}
	if err := checkPorts(ports); err != nil {
		return nil, nil, err
	}
	desired, err := ManagedValues(ports)
	if err != nil {
		return nil, nil, err
	}
	if err := os.MkdirAll(worktreePath, 0o755); err != nil {
		return nil, nil, fmt.Errorf("create worktree dir %q: %w", worktreePath, err)
	}
	path := filepath.Join(worktreePath, EnvFileName)
	raw, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return nil, nil, fmt.Errorf("read .env %q: %w", path, err)
	}
	if os.IsNotExist(err) {
		content, err := Render(ports)
		if err != nil {
			return nil, nil, err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return nil, nil, fmt.Errorf("write .env %q: %w", path, err)
		}
		for k := range desired {
			added = append(added, k)
		}
		sort.Strings(added)
		return added, nil, nil
	}
	content, added, diverged := fillMissing(string(raw), desired)
	if len(added) > 0 {
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return nil, nil, fmt.Errorf("write .env %q: %w", path, err)
		}
	}
	return added, diverged, nil
}

// keepUnmanaged returns the lines of .env content that are not wrk3-managed:
// wrk3 header markers and managed assignments are dropped, everything else
// (user keys, comments, blank lines) is preserved verbatim.
func keepUnmanaged(content string, desired map[string]string) []string {
	body := strings.ReplaceAll(content, "\r\n", "\n")
	lines := strings.Split(body, "\n")
	var kept []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == generatedHeader || trimmed == managedHeader {
			continue
		}
		if key, ok := parseKey(line); ok {
			if _, managed := desired[key]; managed {
				continue
			}
		}
		kept = append(kept, line)
	}
	return kept
}

// trimBlankEnds drops leading/trailing blank lines.
func trimBlankEnds(lines []string) []string {
	for len(lines) > 0 && strings.TrimSpace(lines[0]) == "" {
		lines = lines[1:]
	}
	for len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
		lines = lines[:len(lines)-1]
	}
	return lines
}

// EnsureInherited ensures <worktreePath>/.env like Ensure, except that when
// the worktree has no .env yet, non-managed lines are seeded from the .env at
// seedPath (typically the repo-root checkout) before missing managed keys are
// appended. Managed keys are never inherited — the worktree always gets its
// own allocation. A missing seed file behaves like Ensure, and an existing
// worktree .env is only gap-filled, never reseeded. A seedPath equal to the
// worktree .env is ignored (self-seed).
func EnsureInherited(worktreePath, seedPath string, ports map[string]int) (added []string, diverged map[string]string, err error) {
	if worktreePath == "" {
		return nil, nil, fmt.Errorf("write .env: empty worktree path")
	}
	if err := checkPorts(ports); err != nil {
		return nil, nil, err
	}
	desired, err := ManagedValues(ports)
	if err != nil {
		return nil, nil, err
	}
	if err := os.MkdirAll(worktreePath, 0o755); err != nil {
		return nil, nil, fmt.Errorf("create worktree dir %q: %w", worktreePath, err)
	}
	path := filepath.Join(worktreePath, EnvFileName)
	if _, err := os.Stat(path); err == nil {
		return Ensure(worktreePath, ports)
	} else if !os.IsNotExist(err) {
		return nil, nil, fmt.Errorf("stat .env %q: %w", path, err)
	}
	seed := ""
	if seedPath != "" && seedPath != path {
		raw, err := os.ReadFile(seedPath)
		if err != nil && !os.IsNotExist(err) {
			return nil, nil, fmt.Errorf("read seed .env %q: %w", seedPath, err)
		}
		if err == nil {
			if kept := trimBlankEnds(keepUnmanaged(string(raw), desired)); len(kept) > 0 {
				onlyBlank := true
				for _, l := range kept {
					if strings.TrimSpace(l) != "" {
						onlyBlank = false
						break
					}
				}
				if !onlyBlank {
					seed = strings.Join(kept, "\n")
				}
			}
		}
	}
	if strings.TrimSpace(seed) == "" {
		content, err := Render(ports)
		if err != nil {
			return nil, nil, err
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			return nil, nil, fmt.Errorf("write .env %q: %w", path, err)
		}
		for k := range desired {
			added = append(added, k)
		}
		sort.Strings(added)
		return added, nil, nil
	}
	content, added, diverged := fillMissing(seed, desired)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return nil, nil, fmt.Errorf("write .env %q: %w", path, err)
	}
	return added, diverged, nil
}

// ReadPorts recovers a port allocation from the .env at
// filepath.Join(worktreePath, EnvFileName): for every name in base it reads
// the <NAME>_PORT variable (first assignment wins, like fillMissing).
// It returns the recovered map and ok=false when any name is missing or
// holds no valid TCP port — callers then fall back to a fresh allocation
// instead of adopting a partial/diverged set.
func ReadPorts(worktreePath string, base map[string]int) (recovered map[string]int, ok bool) {
	raw, err := os.ReadFile(filepath.Join(worktreePath, EnvFileName))
	if err != nil {
		return nil, false
	}
	out := make(map[string]int, len(base))
	for name := range base {
		key := EnvVarForPort(name)
		found := false
		for _, line := range strings.Split(string(raw), "\n") {
			v, match := assignmentValue(line, key)
			if !match {
				continue
			}
			n := 0
			for _, r := range v {
				if r < '0' || r > '9' {
					n = -1
					break
				}
				n = n*10 + int(r-'0')
			}
			if n <= 0 || n > 65535 {
				return nil, false
			}
			out[name] = n
			found = true
			break
		}
		if !found {
			return nil, false
		}
	}
	return out, true
}

// StripManaged removes wrk3-managed assignment lines (plus wrk3 header
// markers) from the .env at path, preserving user keys. If nothing but
// blank lines remains, the file is deleted. It returns true when the file
// was deleted. Missing files are a no-op returning false.
func StripManaged(path string, ports map[string]int) (bool, error) {
	desired, err := ManagedValues(ports)
	if err != nil {
		return false, err
	}
	// APP_URL is slug-specific (not part of ManagedValues) but still
	// wrk3-managed: strip it on remove so worktree .env files don't keep
	// stale gateway URLs.
	desired[EnvAppURL] = ""
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read .env %q: %w", path, err)
	}
	kept := trimBlankEnds(keepUnmanaged(string(raw), desired))
	onlyBlank := true
	for _, l := range kept {
		if strings.TrimSpace(l) != "" {
			onlyBlank = false
			break
		}
	}
	if len(kept) == 0 || onlyBlank {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return false, fmt.Errorf("remove .env %q: %w", path, err)
		}
		return true, nil
	}
	out := strings.Join(kept, "\n") + "\n"
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return false, fmt.Errorf("write .env %q: %w", path, err)
	}
	return false, nil
}
