package ports

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

// Generic .env variable names. Per-port vars derive from the port name via
// EnvVarForPort (e.g. `app` -> `APP_PORT`); the BASE_URL family derives
// from the `app` port.
const (
	EnvApp              = "APP_PORT"
	EnvBaseURL          = "BASE_URL"
	EnvWebhooksBaseURL  = "WEBHOOKS_BASE_URL"
	EnvAllowedWSOrigins = "ALLOWED_WS_ORIGINS"
)

// EnvFileName is the generated file name inside each worktree.
const EnvFileName = ".env"

// EnvVarForPort maps a port name to its .env variable (e.g. `app` ->
// `APP_PORT`, `web` -> `WEB_PORT`). Non-alphanumeric runs become a single
// underscore so names like `api-v2` stay valid shell identifiers.
func EnvVarForPort(name string) string {
	var b strings.Builder
	prevUnderscore := true // leading trim: avoid a leading underscore
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToUpper(r))
			prevUnderscore = false
		} else if !prevUnderscore {
			b.WriteByte('_')
			prevUnderscore = true
		}
	}
	s := strings.Trim(b.String(), "_")
	if s == "" {
		return "PORT"
	}
	return s + "_PORT"
}

// appPort extracts the app port for derived URLs.
func appPort(ports map[string]int) (int, error) {
	v, ok := ports[PortApp]
	if !ok {
		return 0, fmt.Errorf("render .env: missing port %q", PortApp)
	}
	return v, nil
}

// ManagedValues maps every wrk3-managed .env variable to its value for
// the given allocation: one <NAME>_PORT per port plus the BASE_URL family
// derived from the app port.
func ManagedValues(ports map[string]int) (map[string]string, error) {
	app, err := appPort(ports)
	if err != nil {
		return nil, err
	}
	out := make(map[string]string, len(ports)+3)
	for name, v := range ports {
		out[EnvVarForPort(name)] = fmt.Sprintf("%d", v)
	}
	origin := fmt.Sprintf("http://localhost:%d", app)
	out[EnvBaseURL] = origin
	out[EnvWebhooksBaseURL] = origin
	out[EnvAllowedWSOrigins] = origin
	return out, nil
}

// managedHeader marks the appended block in pre-existing .env files.
const managedHeader = "# Managed by wrk3 — port allocations (other lines preserved)."

// generatedHeader is written only for fresh .env files. Pre-existing files
// keep their own content; managed keys are upserted under managedHeader.
const generatedHeader = "# Generated by wrk3 — do not edit."

// parseKey extracts the variable name from a .env assignment line.
// It reports ok=false for blank lines, comments, and non-assignments.
// It tolerates `export KEY=...`, surrounding whitespace, and `KEY = ...`.
func parseKey(line string) (key string, ok bool) {
	trimmed := strings.TrimSpace(strings.TrimSuffix(line, "\r"))
	if trimmed == "" || strings.HasPrefix(trimmed, "#") {
		return "", false
	}
	rest := trimmed
	if strings.HasPrefix(rest, "export") && len(rest) > len("export") &&
		(rest[len("export")] == ' ' || rest[len("export")] == '\t') {
		rest = strings.TrimSpace(rest[len("export"):])
	}
	idx := strings.Index(rest, "=")
	if idx < 0 {
		return "", false
	}
	key = strings.TrimSpace(rest[:idx])
	if key == "" {
		return "", false
	}
	for i, r := range key {
		if r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r) {
			if i == 0 && unicode.IsDigit(r) {
				return "", false
			}
			continue
		}
		return "", false
	}
	return key, true
}

// splitComment splits a post-= value into value and trailing comment.
// Only ` <space>#` starts a comment so URLs and quoted `#` survive.
func splitComment(after string) (before, comment string) {
	for i := 0; i < len(after); i++ {
		if after[i] == '#' && i > 0 && (after[i-1] == ' ' || after[i-1] == '\t') {
			return strings.TrimRight(after[:i], " \t"), after[i:]
		}
	}
	return after, ""
}

// updateLine rewrites one assignment line with a new value, preserving the
// leading whitespace, `export` prefix, and any trailing ` # comment`.
func updateLine(line, key, value string) string {
	// Preserve CRLF style per line.
	crlf := strings.HasSuffix(line, "\r")
	work := strings.TrimSuffix(line, "\r")
	eq := strings.Index(work, "=")
	if eq < 0 {
		return line
	}
	left := work[:eq]
	// Reconstruct the left side: leading whitespace + export prefix + KEY.
	lead := work[:len(work)-len(strings.TrimLeft(work, " \t"))]
	trimmedLeft := strings.TrimSpace(left)
	exportPrefix := ""
	if strings.HasPrefix(trimmedLeft, "export") &&
		len(strings.TrimSpace(strings.TrimPrefix(trimmedLeft, "export"))) != len(trimmedLeft) {
		exportPrefix = "export "
	}
	_, comment := splitComment(work[eq+1:])
	newLine := lead + exportPrefix + key + "=" + value
	if comment != "" {
		// splitComment kept the `#...`; ensure single space before it.
		newLine += " " + strings.TrimLeft(comment, " \t")
	}
	if crlf {
		newLine += "\r"
	}
	return newLine
}

// Render builds the .env file content for ports. Every entry in ports
// becomes <NAME>_PORT (sorted by port name for stable output); BASE_URL,
// WEBHOOKS_BASE_URL, and ALLOWED_WS_ORIGINS derive from the app port
// as http://localhost:<appPort>.
func Render(ports map[string]int) (string, error) {
	if len(ports) == 0 {
		return "", fmt.Errorf("render .env: no ports allocated")
	}
	app, err := appPort(ports)
	if err != nil {
		return "", err
	}
	names := make([]string, 0, len(ports))
	for name := range ports {
		names = append(names, name)
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString(generatedHeader + "\n")
	for _, name := range names {
		fmt.Fprintf(&b, "%s=%d\n", EnvVarForPort(name), ports[name])
	}
	origin := fmt.Sprintf("http://localhost:%d", app)
	fmt.Fprintf(&b, "%s=%s\n", EnvBaseURL, origin)
	fmt.Fprintf(&b, "%s=%s\n", EnvWebhooksBaseURL, origin)
	fmt.Fprintf(&b, "%s=%s\n", EnvAllowedWSOrigins, origin)
	return b.String(), nil
}

// Upsert merges managed port values into existing .env content: managed
// keys are updated in place (every occurrence), missing managed keys are
// appended under managedHeader, and all other lines pass through verbatim.
// It never deletes user keys, comments, or blank lines.
func Upsert(existing string, ports map[string]int) (string, error) {
	desired, err := ManagedValues(ports)
	if err != nil {
		return "", err
	}
	// Normalize CRLF to LF for processing; callers write back LF.
	crlf := strings.Contains(existing, "\r\n")
	body := strings.ReplaceAll(existing, "\r\n", "\n")
	lines := strings.Split(body, "\n")
	seen := make(map[string]struct{}, len(desired))
	for i, line := range lines {
		key, ok := parseKey(line)
		if !ok {
			continue
		}
		v, managed := desired[key]
		if !managed {
			continue
		}
		lines[i] = updateLine(line, key, v)
		seen[key] = struct{}{}
	}
	var missing []string
	for k := range desired {
		if _, ok := seen[k]; !ok {
			missing = append(missing, k)
		}
	}
	if len(missing) > 0 {
		sort.Strings(missing)
		// Drop the trailing empty element from Split so we control newlines.
		if len(lines) > 0 && lines[len(lines)-1] == "" {
			lines = lines[:len(lines)-1]
		}
		if len(lines) > 0 && lines[len(lines)-1] != "" {
			lines = append(lines, "")
		}
		hasMarker := false
		for _, l := range lines {
			if strings.TrimSpace(l) == managedHeader {
				hasMarker = true
				break
			}
		}
		if !hasMarker {
			lines = append(lines, managedHeader)
		}
		for _, k := range missing {
			lines = append(lines, k+"="+desired[k])
		}
	}
	out := strings.Join(lines, "\n")
	if out != "" && !strings.HasSuffix(out, "\n") {
		out += "\n"
	}
	if crlf {
		out = strings.ReplaceAll(out, "\n", "\r\n")
	}
	return out, nil
}

// Write upserts <worktreePath>/.env with ports: fresh files get Render()
// output, pre-existing files keep every user line and gain only the managed
// keys (updated in place or appended). It never overwrites secrets.
func Write(worktreePath string, ports map[string]int) error {
	if worktreePath == "" {
		return fmt.Errorf("write .env: empty worktree path")
	}
	if len(ports) == 0 {
		return fmt.Errorf("render .env: no ports allocated")
	}
	if _, err := appPort(ports); err != nil {
		return err
	}
	if err := os.MkdirAll(worktreePath, 0o755); err != nil {
		return fmt.Errorf("create worktree dir %q: %w", worktreePath, err)
	}
	path := filepath.Join(worktreePath, EnvFileName)
	raw, err := os.ReadFile(path)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read .env %q: %w", path, err)
	}
	var content string
	if os.IsNotExist(err) {
		content, err = Render(ports)
		if err != nil {
			return err
		}
	} else {
		content, err = Upsert(string(raw), ports)
		if err != nil {
			return err
		}
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write .env %q: %w", path, err)
	}
	return nil
}

// StripManaged removes wrk3-managed assignment lines (plus wrk3 header
// markers) from the .env at path, preserving user keys. If nothing but
// blank lines remains, the file is deleted. It returns true when the file
// was deleted. Missing files are a no-op returning false.
func StripManaged(path string, ports map[string]int) (bool, error) {
	desired, err := ManagedValues(ports)
	if err != nil {
		return false, err
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, fmt.Errorf("read .env %q: %w", path, err)
	}
	body := strings.ReplaceAll(string(raw), "\r\n", "\n")
	lines := strings.Split(body, "\n")
	var kept []string
	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == generatedHeader || trimmed == managedHeader {
			continue
		}
		if key, ok := parseKey(line); ok {
			if _, managed := desired[key]; managed {
				continue
			}
		}
		kept = append(kept, line)
	}
	// Drop leading/trailing blank lines left by stripping.
	for len(kept) > 0 && strings.TrimSpace(kept[0]) == "" {
		kept = kept[1:]
	}
	for len(kept) > 0 && strings.TrimSpace(kept[len(kept)-1]) == "" {
		kept = kept[:len(kept)-1]
	}
	onlyBlank := true
	for _, l := range kept {
		if strings.TrimSpace(l) != "" {
			onlyBlank = false
			break
		}
	}
	if len(kept) == 0 || onlyBlank {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return false, fmt.Errorf("remove .env %q: %w", path, err)
		}
		return true, nil
	}
	out := strings.Join(kept, "\n") + "\n"
	if err := os.WriteFile(path, []byte(out), 0o644); err != nil {
		return false, fmt.Errorf("write .env %q: %w", path, err)
	}
	return false, nil
}
