package ports

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

// Generic .env variable names. Per-port vars derive from the port name via
// EnvVarForPort (e.g. `app` -> `APP_PORT`); the BASE_URL family derives
// from the `app` port.
const (
	EnvApp              = "APP_PORT"
	EnvBaseURL          = "BASE_URL"
	EnvWebhooksBaseURL  = "WEBHOOKS_BASE_URL"
	EnvAllowedWSOrigins = "ALLOWED_WS_ORIGINS"
)

// EnvFileName is the generated file name inside each worktree.
const EnvFileName = ".env"

// EnvVarForPort maps a port name to its .env variable (e.g. `app` ->
// `APP_PORT`, `web` -> `WEB_PORT`). Non-alphanumeric runs become a single
// underscore so names like `api-v2` stay valid shell identifiers.
func EnvVarForPort(name string) string {
	var b strings.Builder
	prevUnderscore := true // leading trim: avoid a leading underscore
	for _, r := range name {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			b.WriteRune(unicode.ToUpper(r))
			prevUnderscore = false
		} else if !prevUnderscore {
			b.WriteByte('_')
			prevUnderscore = true
		}
	}
	s := strings.Trim(b.String(), "_")
	if s == "" {
		return "PORT"
	}
	return s + "_PORT"
}

// appPort extracts the app port for derived URLs.
func appPort(ports map[string]int) (int, error) {
	v, ok := ports[PortApp]
	if !ok {
		return 0, fmt.Errorf("render .env: missing port %q", PortApp)
	}
	return v, nil
}

// Render builds the .env file content for ports. Every entry in ports
// becomes <NAME>_PORT (sorted by port name for stable output); BASE_URL,
// WEBHOOKS_BASE_URL, and ALLOWED_WS_ORIGINS derive from the app port
// as http://localhost:<appPort>.
func Render(ports map[string]int) (string, error) {
	if len(ports) == 0 {
		return "", fmt.Errorf("render .env: no ports allocated")
	}
	app, err := appPort(ports)
	if err != nil {
		return "", err
	}
	names := make([]string, 0, len(ports))
	for name := range ports {
		names = append(names, name)
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString("# Generated by wrk3 — do not edit.\n")
	for _, name := range names {
		fmt.Fprintf(&b, "%s=%d\n", EnvVarForPort(name), ports[name])
	}
	origin := fmt.Sprintf("http://localhost:%d", app)
	fmt.Fprintf(&b, "%s=%s\n", EnvBaseURL, origin)
	fmt.Fprintf(&b, "%s=%s\n", EnvWebhooksBaseURL, origin)
	fmt.Fprintf(&b, "%s=%s\n", EnvAllowedWSOrigins, origin)
	return b.String(), nil
}

// Write creates <worktreePath>/.env from ports.
func Write(worktreePath string, ports map[string]int) error {
	if worktreePath == "" {
		return fmt.Errorf("write .env: empty worktree path")
	}
	content, err := Render(ports)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(worktreePath, 0o755); err != nil {
		return fmt.Errorf("create worktree dir %q: %w", worktreePath, err)
	}
	path := filepath.Join(worktreePath, EnvFileName)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("write .env %q: %w", path, err)
	}
	return nil
}
