package task

import (
	"fmt"
	"sort"
	"strings"
)

// machineTarget is the "machine" environment: a self-contained shell
// script that runs the task graph directly with `docker run`.
type machineTarget struct{}

func (machineTarget) Name() string { return "machine" }

func (machineTarget) Render(d *Definition) ([]byte, error) {
	if d == nil {
		return nil, fmt.Errorf("task definition is nil")
	}
	plan, err := d.Machine(MachineOptions{Project: d.Name})
	if err != nil {
		return nil, err
	}
	return []byte(plan.Script()), nil
}

func init() { RegisterTarget(machineTarget{}) }

// MachineOptions configures bare-machine rendering.
type MachineOptions struct {
	// Project prefixes container names ("<project>-<service>") and
	// network names ("<project>_<network>"). Empty means bare names.
	Project string
}

// MachinePlan is a dependency-ordered set of docker CLI invocations.
type MachinePlan struct {
	// Networks creates the named networks before any service starts.
	Networks [][]string
	// Up starts services dependencies-first.
	Up [][]string
	// Connect attaches extra networks to a service after it starts.
	Connect [][]string
	// Down removes service containers.
	Down [][]string
	// NetworkDown removes the created networks.
	NetworkDown [][]string
}

// Machine converts the Definition into docker CLI invocations that run it
// directly on a host. Services with only a build context are rejected:
// the machine target does not build images.
func (d *Definition) Machine(opts MachineOptions) (*MachinePlan, error) {
	if d == nil {
		return nil, fmt.Errorf("task definition is nil")
	}
	d.Normalize()
	if err := d.Validate(); err != nil {
		return nil, err
	}
	plan := &MachinePlan{}
	for _, name := range sortedKeys(d.Networks) {
		net := d.Networks[name]
		if net.External {
			continue
		}
		plan.Networks = append(plan.Networks, []string{"docker", "network", "create", opts.networkName(name)})
	}
	for _, name := range d.Order() {
		svc := d.Services[name]
		if svc.Image == "" {
			return nil, fmt.Errorf("machine target: service %q has no image (build contexts are not supported on the machine target; build the image first)", name)
		}
		container := opts.containerName(name)
		plan.Up = append(plan.Up, dockerRunArgs(container, svc, opts))
		for _, net := range svc.Networks[min(1, len(svc.Networks)):] {
			plan.Connect = append(plan.Connect, []string{"docker", "network", "connect", opts.networkName(net), container})
		}
	}
	for i := len(d.Order()) - 1; i >= 0; i-- {
		name := d.Order()[i]
		plan.Down = append(plan.Down, []string{"docker", "rm", "-f", opts.containerName(name)})
	}
	for _, name := range sortedKeys(d.Networks) {
		if d.Networks[name].External {
			continue
		}
		plan.NetworkDown = append(plan.NetworkDown, []string{"docker", "network", "rm", opts.networkName(name)})
	}
	return plan, nil
}

func (o MachineOptions) containerName(service string) string {
	if o.Project == "" {
		return service
	}
	return o.Project + "-" + service
}

func (o MachineOptions) networkName(network string) string {
	if o.Project == "" {
		return network
	}
	return o.Project + "_" + network
}

// dockerRunArgs builds one `docker run` argv for svc.
func dockerRunArgs(container string, svc *Service, opts MachineOptions) []string {
	args := []string{"docker", "run", "-d", "--name", container}
	if svc.Restart != "" {
		args = append(args, "--restart", svc.Restart)
	}
	for _, k := range sortedKeys(svc.Environment) {
		args = append(args, "-e", k+"="+svc.Environment[k])
	}
	for _, k := range sortedKeys(svc.Labels) {
		args = append(args, "--label", k+"="+svc.Labels[k])
	}
	for _, p := range svc.Ports {
		args = append(args, "-p", portSpec(p))
	}
	for _, m := range svc.Volumes {
		args = append(args, "-v", mountSpec(m))
	}
	if len(svc.Networks) > 0 {
		args = append(args, "--network", opts.networkName(svc.Networks[0]))
	}
	if len(svc.Entrypoint) > 0 {
		args = append(args, "--entrypoint", svc.Entrypoint[0])
	}
	args = append(args, svc.Image)
	args = append(args, svc.Command...)
	return args
}

func portSpec(p Port) string {
	host := ""
	if p.HostIP != "" {
		host = p.HostIP + ":"
	}
	spec := fmt.Sprintf("%s%d:%d", host, p.Published, p.Target)
	if p.Published == 0 {
		spec = fmt.Sprintf("%s%d", host, p.Target)
	}
	if p.Protocol != "" && p.Protocol != ProtocolTCP {
		spec += "/" + p.Protocol
	}
	return spec
}

func mountSpec(m Mount) string {
	if m.Source == "" {
		return m.Target
	}
	spec := m.Source + ":" + m.Target
	if m.ReadOnly {
		spec += ":ro"
	}
	return spec
}

// Script renders the plan as a POSIX shell script with `up` (default) and
// `down` subcommands.
func (p *MachinePlan) Script() string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("set -eu\n")
	b.WriteString("# Generated by wrk3 from the task definition.\n")
	b.WriteString("cmd=\"${1:-up}\"\n")
	b.WriteString("case \"$cmd\" in\n")
	b.WriteString("up)\n")
	p.writeGroup(&b, p.Networks)
	p.writeGroup(&b, p.Up)
	p.writeGroup(&b, p.Connect)
	b.WriteString("  ;;\n")
	b.WriteString("down)\n")
	p.writeGroup(&b, p.Down)
	p.writeGroup(&b, p.NetworkDown)
	b.WriteString("  ;;\n")
	b.WriteString("*)\n")
	b.WriteString("  echo \"usage: $0 {up|down}\" >&2\n")
	b.WriteString("  exit 2\n")
	b.WriteString("  ;;\n")
	b.WriteString("esac\n")
	return b.String()
}

func (p *MachinePlan) writeGroup(b *strings.Builder, group [][]string) {
	if len(group) == 0 {
		return
	}
	for _, argv := range group {
		b.WriteString("  ")
		for i, a := range argv {
			if i > 0 {
				b.WriteByte(' ')
			}
			b.WriteString(shellQuote(a))
		}
		b.WriteByte('\n')
	}
}

// shellQuote wraps s in single quotes unless it is already safe.
func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	safe := true
	for _, r := range s {
		ok := r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' ||
			strings.ContainsRune("_-./:=@,", r)
		if !ok {
			safe = false
			break
		}
	}
	if safe {
		return s
	}
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// sortedKeys returns the keys of m in sorted order.
func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
