package task

import (
	"bytes"
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"
)

type kv struct {
	k string
	v any
}

type orderedMap []kv

func (m orderedMap) MarshalYAML() (any, error) {
	node := &yaml.Node{Kind: yaml.MappingNode}
	for _, p := range m {
		if p.v == nil {
			continue
		}
		k := &yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: p.k}
		var v yaml.Node
		if err := v.Encode(p.v); err != nil {
			return nil, err
		}
		node.Content = append(node.Content, k, &v)
	}
	return node, nil
}

func marshalYAML(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(v); err != nil {
		_ = enc.Close()
		return nil, err
	}
	if err := enc.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func header(env Environment, t Task) string {
	src := string(t.Source.Kind)
	if src == "" {
		src = "unknown"
	}
	return fmt.Sprintf("# generated by wrk3 for %s from %s; source files were not modified\n", env, src)
}

func envPairs(env map[string]string) orderedMap {
	if len(env) == 0 {
		return nil
	}
	keys := make([]string, 0, len(env))
	for k := range env {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	out := make(orderedMap, 0, len(keys))
	for _, k := range keys {
		out = append(out, kv{k, env[k]})
	}
	return out
}
